# Generated by Django 5.2.8 on 2025-12-01 22:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proposal',
            new_name='proposals_p_documen_284b9d_idx',
            old_name='proposals_p_document_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='proposals_p_proposa_f90f56_idx',
            old_name='proposals_p_proposal_number_idx',
        ),
        migrations.AlterField(
            model_name='proposaltemplate',
            name='profit_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='proposaltemplate',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.19'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
