# Cloud Build Configuration for DraftCraft V1
# Semi-Automated CI/CD Pipeline - Manual trigger, automated test → build → deploy
# Region: europe-west3 (Frankfurt, GDPR-compliant)

steps:
  # Step 1: Run Tests
  # Fail fast if tests don't pass - ensures quality before deployment
  - name: 'gcr.io/cloud-builders/docker'
    id: 'run-tests'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/app'
      - '-w'
      - '/app/backend'
      - 'python:3.11-slim'
      - 'bash'
      - '-c'
      - |
        pip install --quiet -r requirements/base.txt -r requirements/production.txt -r requirements/development.txt
        pytest --cov=. --cov-report=term -v --tb=short || exit 1
    timeout: '600s'

  # Step 2: Build Docker Image
  # Multi-stage build optimized for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/draftcraft:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/draftcraft:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/draftcraft:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/draftcraft:latest'
      - '.'
    waitFor: ['run-tests']
    timeout: '1200s'

  # Step 3: Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-sha'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/draftcraft:$SHORT_SHA'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-build'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/draftcraft:$BUILD_ID'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/draftcraft:latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run (europe-west3)
  # NOTE: Secrets and Cloud SQL connection must be pre-configured
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'draftcraft'
      - '--image=gcr.io/$PROJECT_ID/draftcraft:$SHORT_SHA'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300s'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-cloudsql-instances=${_CLOUD_SQL_CONNECTION}'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=config.settings.production,GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets=DJANGO_SECRET_KEY=DJANGO_SECRET_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest'
    waitFor: ['push-image-sha', 'push-image-build', 'push-image-latest']
    timeout: '600s'

# Substitutions for environment-specific values
substitutions:
  _CLOUD_SQL_CONNECTION: 'PROJECT_ID:europe-west3:draftcraft-db'
  _DEPLOY_ENV: 'production'

# Build configuration
options:
  # Use high-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'

  # Log streaming for real-time feedback
  logging: CLOUD_LOGGING_ONLY

  # Docker layer caching for faster rebuilds
  dynamic_substitutions: true

# Build timeout (total for all steps)
timeout: '3600s'

# Images to push to registry
images:
  - 'gcr.io/$PROJECT_ID/draftcraft:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/draftcraft:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/draftcraft:latest'

# Build artifacts
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts'
    paths:
      - 'backend/staticfiles/**'
