# Generated by Django 5.2.8 on 2025-12-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='extractedentity',
            new_name='extraction__documen_b44341_idx',
            old_name='extraction_e_document_id_entity_type_idx',
        ),
    ]
