# Generated by Django 5.0 on 2025-11-27 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("template_create", "Template Created"),
                            ("template_update", "Template Updated"),
                            ("template_delete", "Template Deleted"),
                            ("holzart_enable", "Wood Type Enabled"),
                            ("holzart_disable", "Wood Type Disabled"),
                            ("holzart_update", "Wood Type Price/Factor Updated"),
                            ("material_add", "Material Added to List"),
                            ("material_update", "Material Updated"),
                            ("material_remove", "Material Removed"),
                            ("seasonal_create", "Seasonal Campaign Created"),
                            ("seasonal_update", "Seasonal Campaign Updated"),
                            ("seasonal_delete", "Seasonal Campaign Deleted"),
                            ("pattern_fix_apply", "Pattern Fix Applied"),
                            (
                                "confidence_threshold_update",
                                "Confidence Threshold Updated",
                            ),
                            ("field_weight_update", "Field Weight Updated"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Previous value (before change)",
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, default=dict, help_text="New value (after change)"
                    ),
                ),
                (
                    "affected_documents",
                    models.IntegerField(
                        default=0,
                        help_text="How many documents could be affected by this change",
                    ),
                ),
                ("reasoning", models.TextField(help_text="Why this change was made")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("applied", "Applied"),
                            ("reverted", "Reverted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Application status",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status_reason",
                    models.TextField(
                        blank=True, help_text="Reason for approval/rejection"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "retention_until",
                    models.DateTimeField(
                        help_text="After this date, this record can be deleted (DSGVO Art. 17)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Action Audit",
                "verbose_name_plural": "Admin Action Audits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partial_failure", "Partial Failure"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_count", models.IntegerField(default=0)),
                ("processed_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cloud_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BetriebskennzahlTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Standard Woodcraft Factors 2024')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of template and its application",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Version string (e.g., '1.0', '2.1') for tracking changes",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Active templates are available for company selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Betriebskennzahl Template",
                "verbose_name_plural": "Betriebskennzahl Templates",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionFailurePattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field being extracted (e.g., amount, vendor_name)",
                        max_length=100,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("low_confidence", "Low Confidence Field"),
                            ("missing_field", "Missing Field"),
                            ("formatting_error", "Formatting Error"),
                            ("data_mismatch", "Data Mismatch"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "root_cause",
                    models.CharField(
                        help_text="Why the pattern occurs", max_length=200
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical - Immediate attention needed"),
                            ("HIGH", "High - Important to fix"),
                            ("MEDIUM", "Medium - Should be addressed"),
                            ("LOW", "Low - Nice to have"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.70"),
                        help_text="Average confidence of this pattern",
                        max_digits=5,
                    ),
                ),
                (
                    "affected_document_count",
                    models.IntegerField(
                        default=0, help_text="Number of documents affected"
                    ),
                ),
                (
                    "total_occurrences",
                    models.IntegerField(
                        default=0, help_text="Total times pattern occurred"
                    ),
                ),
                (
                    "example_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of affected document IDs",
                    ),
                ),
                (
                    "suggested_fix",
                    models.TextField(
                        blank=True, help_text="Suggested fix or improvement"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on this pattern"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Pattern is being tracked"
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Pattern has been reviewed by admin"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When pattern was reviewed", null=True
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("resolution_deadline", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Extraction Failure Pattern",
                "verbose_name_plural": "Extraction Failure Patterns",
                "ordering": ["-severity", "-affected_document_count"],
            },
        ),
        migrations.CreateModel(
            name="HolzartKennzahl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "holzart",
                    models.CharField(
                        help_text="German wood name (e.g., 'eiche', 'buche', 'kiefer', 'fichte')",
                        max_length=50,
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("hartholz", "Hartholz (Hardwood)"),
                            ("weichholz", "Weichholz (Softwood)"),
                            ("exotisch", "Exotisch (Exotic)"),
                        ],
                        default="hartholz",
                        max_length=20,
                    ),
                ),
                (
                    "preis_faktor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Multiplier for base price (1.0 = base, 1.3 = 30% premium)",
                        max_digits=5,
                    ),
                ),
                (
                    "verfuegbarkeit",
                    models.CharField(
                        choices=[
                            ("staendig", "Ständig verfügbar (Always Available)"),
                            ("saisonal", "Saisonal (Seasonal)"),
                            ("bestellen", "Auf Bestellung (On Order)"),
                            ("selten", "Selten (Rare)"),
                        ],
                        default="staendig",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Can be disabled to hide from calculations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Holzart Kennzahl",
                "verbose_name_plural": "Holzart Kennzahlen",
                "ordering": ["kategorie", "holzart"],
            },
        ),
        migrations.CreateModel(
            name="IndividuelleBetriebskennzahl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "betriebskosten_umlage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly overhead costs (e.g., rent, utilities, insurance)",
                        max_digits=8,
                    ),
                ),
                (
                    "gewinnmarge_prozent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.00"),
                        help_text="Target profit margin as percentage (25% = 0.25)",
                        max_digits=5,
                    ),
                ),
                (
                    "stundensatz_arbeit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("85.00"),
                        help_text="Labor hourly rate in EUR",
                        max_digits=8,
                    ),
                ),
                (
                    "use_handwerk_standard",
                    models.BooleanField(
                        default=True,
                        help_text="Enable Holzart, Oberflächenbearbeitung, Komplexität factors from template",
                    ),
                ),
                (
                    "use_custom_materials",
                    models.BooleanField(
                        default=False,
                        help_text="Enable custom material list (overrides global materials)",
                    ),
                ),
                (
                    "use_seasonal_adjustments",
                    models.BooleanField(
                        default=False, help_text="Enable seasonal pricing adjustments"
                    ),
                ),
                (
                    "use_customer_discounts",
                    models.BooleanField(
                        default=False, help_text="Enable customer-specific discounts"
                    ),
                ),
                (
                    "use_bulk_discounts",
                    models.BooleanField(
                        default=False, help_text="Enable quantity-based bulk discounts"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive companies won't use these metrics",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Individuelle Betriebskennzahl",
                "verbose_name_plural": "Individuelle Betriebskennzahlen",
            },
        ),
        migrations.CreateModel(
            name="KomplexitaetKennzahl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "technik",
                    models.CharField(
                        help_text="German technique name (e.g., 'gedrechselt', 'gefraest', 'geschnitzt', 'hand_geschnitzt', 'intarsia')",
                        max_length=50,
                    ),
                ),
                (
                    "preis_faktor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Price multiplier for this technique",
                        max_digits=4,
                    ),
                ),
                (
                    "zeit_faktor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Labor time multiplier for this technique",
                        max_digits=4,
                    ),
                ),
                (
                    "schwierigkeitsgrad",
                    models.IntegerField(
                        choices=[
                            (1, "Einfach (Easy)"),
                            (2, "Mittel (Medium)"),
                            (3, "Schwierig (Hard)"),
                        ],
                        default=1,
                        help_text="Difficulty level (affects routing and validation)",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Komplexität Kennzahl",
                "verbose_name_plural": "Komplexität Kennzahlen",
                "ordering": ["schwierigkeitsgrad", "technik"],
            },
        ),
        migrations.CreateModel(
            name="MateriallistePosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        help_text="Material description (e.g., 'Eichenbretter 25mm, A-Qualität')",
                        max_length=200,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Internal SKU/Material code", max_length=50
                    ),
                ),
                (
                    "lieferant",
                    models.CharField(help_text="Supplier name", max_length=100),
                ),
                (
                    "standardkosten_eur",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit from supplier (EUR)",
                        max_digits=10,
                    ),
                ),
                (
                    "verpackungseinheit",
                    models.CharField(
                        default="1",
                        help_text="Packaging unit (e.g., '50 Bretter', '25kg', '1 Stk')",
                        max_length=50,
                    ),
                ),
                (
                    "verfuegbarkeit",
                    models.CharField(
                        choices=[
                            ("staendig", "Ständig (Always)"),
                            ("saisonal", "Saisonal (Seasonal)"),
                            ("selten", "Selten (Rare)"),
                            ("bestellen", "Auf Bestellung (On Order)"),
                        ],
                        default="staendig",
                        max_length=20,
                    ),
                ),
                (
                    "rabatt_ab_100",
                    models.IntegerField(
                        default=0, help_text="Discount percentage when quantity >= 100"
                    ),
                ),
                (
                    "rabatt_ab_500",
                    models.IntegerField(
                        default=0, help_text="Discount percentage when quantity >= 500"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Can be disabled to exclude from calculations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Materialliste Position",
                "verbose_name_plural": "Materialliste Positionen",
                "ordering": ["material_name"],
            },
        ),
        migrations.CreateModel(
            name="OberflächenbearbeitungKennzahl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bearbeitung",
                    models.CharField(
                        help_text="German surface treatment name (e.g., 'schleifen', 'lackieren', 'oelen', 'wachsen')",
                        max_length=50,
                    ),
                ),
                (
                    "preis_faktor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Price multiplier for this finish",
                        max_digits=4,
                    ),
                ),
                (
                    "zeit_faktor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Labor time multiplier for this finish",
                        max_digits=4,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Oberflächenbearbeitung Kennzahl",
                "verbose_name_plural": "Oberflächenbearbeitung Kennzahlen",
                "ordering": ["bearbeitung"],
            },
        ),
        migrations.CreateModel(
            name="PatternFixProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Fix title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="What is being changed and why"),
                ),
                (
                    "fix_type",
                    models.CharField(
                        choices=[
                            ("confidence_threshold", "Adjust Confidence Threshold"),
                            ("field_weight", "Update Field Weight"),
                            ("extraction_logic", "Improve Extraction Logic"),
                            ("validation_rule", "Add Validation Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "change_details",
                    models.JSONField(
                        default=dict, help_text="Detailed changes (old → new)"
                    ),
                ),
                (
                    "affected_field",
                    models.CharField(
                        help_text="Which field is affected", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("testing", "Testing"),
                            ("validated", "Validated"),
                            ("deployed", "Deployed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "test_sample_size",
                    models.IntegerField(default=0, help_text="Number of test cases"),
                ),
                (
                    "test_success_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Success rate in testing (0-1)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(blank=True, help_text="Notes from validation"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.80"),
                        help_text="Admin confidence in this fix (0-1)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pattern Fix Proposal",
                "verbose_name_plural": "Pattern Fix Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatternReviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Not started"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved - Ready to apply"),
                            ("rejected", "Rejected - Needs more work"),
                            ("applied", "Applied - Changes deployed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Review session title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="What changes are being reviewed"),
                ),
                (
                    "reviewed_cases_count",
                    models.IntegerField(
                        default=0, help_text="Number of cases reviewed"
                    ),
                ),
                (
                    "approved_cases",
                    models.IntegerField(default=0, help_text="Cases approved for fix"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Why pattern was rejected"),
                ),
                (
                    "estimated_impact",
                    models.CharField(
                        choices=[
                            ("low", "Low Impact"),
                            ("medium", "Medium Impact"),
                            ("high", "High Impact"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("estimated_documents_improved", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_deployment", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pattern Review Session",
                "verbose_name_plural": "Pattern Review Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaisonaleMarge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Campaign name (e.g., 'Weihnachts-Rabatt 2024')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the campaign"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("prozent", "Prozentsatz (%)"),
                            ("absolute", "Absolute Summe (€)"),
                        ],
                        help_text="Percentage or absolute amount",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g., 10) or absolute amount (e.g., 50.00)",
                        max_digits=8,
                    ),
                ),
                ("start_date", models.DateField(help_text="Campaign start date")),
                ("end_date", models.DateField(help_text="Campaign end date")),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("alle", "Alle Projekte (All Projects)"),
                            (
                                "bestehende_kunden",
                                "Bestehende Kunden (Existing Customers)",
                            ),
                            ("neue_kunden", "Neue Kunden (New Customers)"),
                            ("kampagne", "Kampagne-Spezifisch (Campaign-Specific)"),
                        ],
                        help_text="Which customers/projects qualify",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Can be disabled without deleting"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Saisonale Marge",
                "verbose_name_plural": "Saisonale Margen",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="documents_a_documen_2a638b_idx",
            old_name="documents_a_document_id_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="documents_a_user_id_481fbb_idx",
            old_name="documents_a_user_id_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_user_id_ffacf2_idx",
            old_name="documents_d_user_id_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_status_07369e_idx",
            old_name="documents_d_status_idx",
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="agent_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Agent confidence score after enhancement",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="agent_enhanced",
            field=models.BooleanField(
                default=False, help_text="Was result enhanced by Gemini agent"
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="requires_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for human review by agent"
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="review_reasons",
            field=models.JSONField(
                blank=True, default=list, help_text="Reasons why review is needed"
            ),
        ),
        migrations.AddField(
            model_name="adminactionaudit",
            name="admin_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminactionaudit",
            name="affected_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Affected user (null = global change)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affected_by_admin_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminactionaudit",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_admin_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batchdocument",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.batch",
            ),
        ),
        migrations.AddField(
            model_name="batchdocument",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_documents",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="betriebskennzahltemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="betriebskennzahl_templates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extractionfailurepattern",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extractionfailurepattern",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extraction_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holzartkennzahl",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holzarten",
                to="documents.betriebskennzahltemplate",
            ),
        ),
        migrations.AddField(
            model_name="individuellebetriebskennzahl",
            name="handwerk_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Global standards template (if using global metrics)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.betriebskennzahltemplate",
            ),
        ),
        migrations.AddField(
            model_name="individuellebetriebskennzahl",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="betriebskennzahl",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="komplexitaetkennzahl",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="komplexitaeten",
                to="documents.betriebskennzahltemplate",
            ),
        ),
        migrations.AddField(
            model_name="materiallisteposition",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_liste",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="oberflächenbearbeitungkennzahl",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oberflaechenbearbeitungen",
                to="documents.betriebskennzahltemplate",
            ),
        ),
        migrations.AddField(
            model_name="patternfixproposal",
            name="deployed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deployed_fixes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patternfixproposal",
            name="pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fix_proposals",
                to="documents.extractionfailurepattern",
            ),
        ),
        migrations.AddField(
            model_name="patternreviewsession",
            name="admin_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pattern_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patternreviewsession",
            name="pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_sessions",
                to="documents.extractionfailurepattern",
            ),
        ),
        migrations.AddField(
            model_name="patternfixproposal",
            name="review_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fix_proposals",
                to="documents.patternreviewsession",
            ),
        ),
        migrations.AddField(
            model_name="saisonalemarge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saisonale_margen",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(
                fields=["admin_user", "-timestamp"],
                name="documents_a_admin_u_fb4d2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(
                fields=["affected_user", "-timestamp"],
                name="documents_a_affecte_26ad36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(
                fields=["status", "action_type"], name="documents_a_status_93cbd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(
                fields=["retention_until"], name="documents_a_retenti_d09a13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["user", "-created_at"], name="documents_b_user_id_f99add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["status"], name="documents_b_status_07c698_idx"),
        ),
        migrations.AddIndex(
            model_name="batchdocument",
            index=models.Index(
                fields=["batch", "status"], name="documents_b_batch_i_22aaaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchdocument",
            index=models.Index(
                fields=["document"], name="documents_b_documen_61a5c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batchdocument",
            unique_together={("batch", "document")},
        ),
        migrations.AddIndex(
            model_name="betriebskennzahltemplate",
            index=models.Index(
                fields=["is_active", "-updated_at"],
                name="documents_b_is_acti_5076bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="betriebskennzahltemplate",
            index=models.Index(
                fields=["created_by"], name="documents_b_created_f7d223_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionfailurepattern",
            index=models.Index(
                fields=["user", "is_reviewed", "severity"],
                name="documents_e_user_id_f7d317_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="extractionfailurepattern",
            index=models.Index(
                fields=["user", "field_name"], name="documents_e_user_id_5aa8d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionfailurepattern",
            index=models.Index(
                fields=["severity", "is_active"], name="documents_e_severit_460a4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holzartkennzahl",
            index=models.Index(
                fields=["template", "kategorie"], name="documents_h_templat_e34539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holzartkennzahl",
            index=models.Index(
                fields=["template", "is_enabled"], name="documents_h_templat_286346_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holzartkennzahl",
            unique_together={("template", "holzart")},
        ),
        migrations.AddIndex(
            model_name="individuellebetriebskennzahl",
            index=models.Index(
                fields=["user", "is_active"], name="documents_i_user_id_5f0f94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individuellebetriebskennzahl",
            index=models.Index(
                fields=["handwerk_template"], name="documents_i_handwer_d3d0c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="komplexitaetkennzahl",
            index=models.Index(
                fields=["template", "schwierigkeitsgrad"],
                name="documents_k_templat_9b4280_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="komplexitaetkennzahl",
            index=models.Index(
                fields=["template", "is_enabled"], name="documents_k_templat_102ed4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="komplexitaetkennzahl",
            unique_together={("template", "technik")},
        ),
        migrations.AddIndex(
            model_name="materiallisteposition",
            index=models.Index(
                fields=["user", "is_enabled"], name="documents_m_user_id_aab1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materiallisteposition",
            index=models.Index(
                fields=["user", "lieferant"], name="documents_m_user_id_60da3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materiallisteposition",
            index=models.Index(fields=["sku"], name="documents_m_sku_b7f9d2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="materiallisteposition",
            unique_together={("user", "sku")},
        ),
        migrations.AddIndex(
            model_name="oberflächenbearbeitungkennzahl",
            index=models.Index(
                fields=["template", "is_enabled"], name="documents_o_templat_1d2ebd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="oberflächenbearbeitungkennzahl",
            unique_together={("template", "bearbeitung")},
        ),
        migrations.AddIndex(
            model_name="patternreviewsession",
            index=models.Index(
                fields=["pattern", "status"], name="documents_p_pattern_14c903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patternreviewsession",
            index=models.Index(
                fields=["admin_user", "-created_at"],
                name="documents_p_admin_u_e63170_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patternfixproposal",
            index=models.Index(
                fields=["pattern", "status"], name="documents_p_pattern_e45229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patternfixproposal",
            index=models.Index(
                fields=["review_session", "status"],
                name="documents_p_review__add8c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saisonalemarge",
            index=models.Index(
                fields=["user", "is_active", "start_date"],
                name="documents_s_user_id_2cd3d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saisonalemarge",
            index=models.Index(
                fields=["start_date", "end_date"], name="documents_s_start_d_43d48b_idx"
            ),
        ),
    ]
