# Generated by Django 5.2.8 on 2025-11-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_phase3_regenerated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_level', models.CharField(choices=[('high', 'Hohe Sicherheit'), ('medium', 'Mittlere Sicherheit'), ('low', 'Niedrige Sicherheit')], help_text='Traffic light indicator for calculation reliability', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=3, help_text='Confidence score 0.000-1.000 (higher = more reliable)', max_digits=4)),
                ('total_price_eur', models.DecimalField(decimal_places=2, help_text='Final calculated price in EUR', max_digits=10)),
                ('similar_projects_count', models.IntegerField(default=0, help_text='Number of similar projects in user history used for calculation')),
                ('user_average_for_type', models.DecimalField(blank=True, decimal_places=2, help_text="User's average price for this project type (null if no history)", max_digits=10, null=True)),
                ('deviation_from_average_percent', models.DecimalField(blank=True, decimal_places=2, help_text='How much this differs from user average (positive or negative %)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_result', models.OneToOneField(help_text='ExtractionResult this explanation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calculation_explanation', to='documents.extractionresult')),
            ],
            options={
                'verbose_name': 'Calculation Explanation',
                'verbose_name_plural': 'Calculation Explanations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(help_text="German craftsman-friendly name (e.g., 'Materialkosten', 'Zeitaufwand')", max_length=100)),
                ('factor_category', models.CharField(help_text="Category for grouping (e.g., 'material', 'labor', 'overhead')", max_length=50)),
                ('amount_eur', models.DecimalField(decimal_places=2, help_text='Amount in EUR contributed by this factor', max_digits=10)),
                ('impact_percent', models.DecimalField(decimal_places=2, help_text='Percentage of total price (0.00-100.00)', max_digits=5)),
                ('explanation_text', models.TextField(help_text='Plain German explanation for craftsmen (no technical jargon)')),
                ('data_source', models.CharField(choices=[('tier1_global', 'TIER 1 - Globaler Standard'), ('tier2_company', 'TIER 2 - Firmenwerte'), ('tier3_dynamic', 'TIER 3 - Saisonale/Kunden-Anpassung'), ('user_history', 'Ihre bisherigen Projekte')], help_text='Where this value comes from (transparency)', max_length=50)),
                ('is_adjustable', models.BooleanField(default=True, help_text='Can user manually adjust this factor?')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (0 = first, higher = later)')),
                ('explanation', models.ForeignKey(help_text='Parent calculation explanation', on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='documents.calculationexplanation')),
            ],
            options={
                'verbose_name': 'Calculation Factor',
                'verbose_name_plural': 'Calculation Factors',
                'ordering': ['display_order', '-impact_percent'],
            },
        ),
        migrations.CreateModel(
            name='UserProjectBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(help_text="Project type identifier (e.g., 'Badezimmer-Fliesen', 'Küche-Elektrik')", max_length=100)),
                ('total_projects', models.IntegerField(default=0, help_text='Number of completed projects of this type')),
                ('average_price_eur', models.DecimalField(decimal_places=2, help_text='Average final price across all projects', max_digits=10)),
                ('min_price_eur', models.DecimalField(decimal_places=2, help_text='Lowest price for this project type', max_digits=10)),
                ('max_price_eur', models.DecimalField(decimal_places=2, help_text='Highest price for this project type', max_digits=10)),
                ('average_margin_percent', models.DecimalField(decimal_places=2, help_text='Average profit margin percentage', max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='Last time these statistics were updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns these benchmarks', on_delete=django.db.models.deletion.CASCADE, related_name='project_benchmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Project Benchmark',
                'verbose_name_plural': 'User Project Benchmarks',
                'ordering': ['-last_calculated'],
            },
        ),
        migrations.AddIndex(
            model_name='calculationexplanation',
            index=models.Index(fields=['extraction_result'], name='documents_c_extract_bbd592_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationexplanation',
            index=models.Index(fields=['confidence_level', '-created_at'], name='documents_c_confide_c5d8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationfactor',
            index=models.Index(fields=['explanation', 'display_order'], name='documents_c_explana_9a09f7_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationfactor',
            index=models.Index(fields=['factor_category'], name='documents_c_factor__7c508a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectbenchmark',
            index=models.Index(fields=['user', 'project_type'], name='documents_u_user_id_45e786_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectbenchmark',
            index=models.Index(fields=['user', '-last_calculated'], name='documents_u_user_id_6f7f8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprojectbenchmark',
            unique_together={('user', 'project_type')},
        ),
    ]
