# Generated by Django 5.2.8 on 2025-12-03 10:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_enable_rls_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., "Getting Started", "Data Import")', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version (auto-generated from name)', max_length=100, unique=True)),
                ('icon', models.CharField(choices=[('📚', 'Books - General Documentation'), ('🚀', 'Rocket - Getting Started'), ('📤', 'Upload - Data Import/Export'), ('⚙️', 'Settings - Configuration'), ('🧪', 'Test Tube - Testing'), ('🐛', 'Bug - Troubleshooting'), ('💡', 'Lightbulb - Tips & Tricks'), ('🔧', 'Wrench - Advanced Features'), ('📊', 'Chart - Reports & Analytics'), ('🔐', 'Lock - Security & Permissions')], default='📚', help_text='Icon to display in admin', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Hide category if inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wiki Category',
                'verbose_name_plural': 'Wiki Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title (clear and descriptive)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(help_text='URL-friendly version', max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Short summary (appears in article list)', max_length=500)),
                ('content', models.TextField(help_text='Full article content (Markdown supported)')),
                ('content_html', models.TextField(blank=True, editable=False, help_text='Auto-generated HTML from Markdown')),
                ('difficulty', models.CharField(choices=[('beginner', '🟢 Beginner - Easy to follow'), ('intermediate', '🟡 Intermediate - Some experience needed'), ('advanced', '🔴 Advanced - Expert level')], default='beginner', help_text='Difficulty level', max_length=20)),
                ('estimated_time', models.CharField(blank=True, help_text='Estimated reading time (e.g., "5 minutes", "10-15 minutes")', max_length=50)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search (e.g., "upload, excel, import")', max_length=200)),
                ('source_file', models.CharField(blank=True, help_text='Original markdown file path (for auto-sync)', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time synced from source file', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Show article to users')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section on wiki home')),
                ('view_count', models.IntegerField(default=0, editable=False, help_text='Number of times viewed')),
                ('helpful_count', models.IntegerField(default=0, editable=False, help_text='Number of "helpful" votes')),
                ('not_helpful_count', models.IntegerField(default=0, editable=False, help_text='Number of "not helpful" votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When article was first published', null=True)),
                ('created_by', models.ForeignKey(help_text='Article author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_articles_created', to=settings.AUTH_USER_MODEL)),
                ('related_articles', models.ManyToManyField(blank=True, help_text='Related articles to show at the end', to='documents.wikiarticle')),
                ('updated_by', models.ForeignKey(help_text='Last person to update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_articles_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category for organization', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='documents.wikicategory')),
            ],
            options={
                'verbose_name': 'Wiki Article',
                'verbose_name_plural': 'Wiki Articles',
                'ordering': ['-is_featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='Was this article helpful?')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='documents.wikiarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiki Feedback',
                'verbose_name_plural': 'Wiki Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Search query', max_length=200)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results found')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who searched (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiki Search Log',
                'verbose_name_plural': 'Wiki Search Logs',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['category', 'is_published'], name='documents_w_categor_922a91_idx'),
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['slug'], name='documents_w_slug_7660e7_idx'),
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['-view_count'], name='documents_w_view_co_d029cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wikisearchlog',
            index=models.Index(fields=['query'], name='documents_w_query_2d28c6_idx'),
        ),
        migrations.AddIndex(
            model_name='wikisearchlog',
            index=models.Index(fields=['-searched_at'], name='documents_w_searche_de84a3_idx'),
        ),
    ]
