# Generated by Django 5.0 on 2025-12-07 21:16

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0005_wikicategory_wikiarticle_wikifeedback_wikisearchlog_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetriebspauschaleRegel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name der Pauschale (z.B. 'Anfahrt Standard')",
                        max_length=200,
                    ),
                ),
                (
                    "pauschale_typ",
                    models.CharField(
                        choices=[
                            ("anfahrt", "Anfahrt"),
                            ("entsorgung", "Entsorgung"),
                            ("montage", "Montage/Installation"),
                            ("kleinauftrag", "Kleinauftragszuschlag"),
                            ("verpackung", "Verpackung/Versand"),
                            ("planung", "Planungs-/Beratungskosten"),
                            ("miete", "Geräte-/Werkzeugmiete"),
                            ("genehmigung", "Genehmigungsgebühren"),
                            ("sonstiges", "Sonstige Pauschale"),
                        ],
                        help_text="Art der Pauschale",
                        max_length=20,
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(blank=True, help_text="Detaillierte Beschreibung"),
                ),
                (
                    "berechnungsart",
                    models.CharField(
                        choices=[
                            ("fest", "Fester Betrag"),
                            ("pro_einheit", "Pro Einheit (m³, km, etc.)"),
                            ("prozent", "Prozentsatz vom Auftragswert"),
                            ("konditional", "Konditional (IF-THEN-ELSE)"),
                        ],
                        default="fest",
                        help_text="Wie wird diese Pauschale berechnet?",
                        max_length=20,
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Betrag in EUR (für 'fest') oder Preis pro Einheit (für 'pro_einheit')",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "einheit",
                    models.CharField(
                        choices=[
                            ("eur", "EUR"),
                            ("km", "Kilometer"),
                            ("m3", "Kubikmeter"),
                            ("h", "Stunden"),
                            ("stk", "Stück"),
                            ("prozent", "Prozent"),
                        ],
                        default="eur",
                        help_text="Einheit für 'pro_einheit' Berechnung",
                        max_length=20,
                    ),
                ),
                (
                    "prozentsatz",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prozentsatz (z.B. 5.00 für 5%)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "konditional_regel",
                    models.JSONField(
                        blank=True,
                        help_text='\n        JSON-Regel für konditionale Logik (Level 2 DSL).\n\n        Beispiel:\n        {\n            "operation": "IF_THEN_ELSE",\n            "bedingung": {\n                "operation": "GREATER_THAN",\n                "links": {"quelle": "distanz_km"},\n                "rechts": 50\n            },\n            "dann": {"betrag": 100.00},\n            "sonst": {"betrag": 50.00}\n        }\n        ',
                        null=True,
                    ),
                ),
                (
                    "min_auftragswert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimaler Auftragswert für Anwendung (leer = keine Bedingung)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_auftragswert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximaler Auftragswert für Anwendung (leer = keine Bedingung)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ist_aktiv",
                    models.BooleanField(
                        default=True, help_text="Ist diese Pauschale aktiv?"
                    ),
                ),
                (
                    "prioritaet",
                    models.IntegerField(
                        default=100,
                        help_text="Niedrigere Zahl = höhere Priorität (bei mehreren Pauschalen gleichen Typs)",
                    ),
                ),
                (
                    "gueltig_ab",
                    models.DateField(
                        blank=True,
                        help_text="Ab wann ist diese Pauschale gültig?",
                        null=True,
                    ),
                ),
                (
                    "gueltig_bis",
                    models.DateField(
                        blank=True,
                        help_text="Bis wann ist diese Pauschale gültig?",
                        null=True,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "zusatz_daten",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusätzliche Konfiguration (z.B. Distanzberechnung, Entsorgungsklassen)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Firma/User für diese Pauschale",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betriebspauschalen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Betriebspauschale-Regel",
                "verbose_name_plural": "Betriebspauschale-Regeln",
                "ordering": ["pauschale_typ", "prioritaet", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gewerk",
                    models.CharField(
                        choices=[
                            ("tischler", "Tischler/Schreiner"),
                            ("zimmerer", "Zimmerer"),
                            ("polsterer", "Polsterer"),
                            ("allgemein", "Gewerkübergreifend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="company_profiles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmen",
            },
        ),
        migrations.CreateModel(
            name="BauteilKatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name des Katalogs (z.B. 'Beschlagskatalog Q1 2025')",
                        max_length=200,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Versions-Nummer (z.B. '2025.1', 'Q1-2025')",
                        max_length=50,
                    ),
                ),
                (
                    "gewerk",
                    models.CharField(
                        choices=[
                            ("tischler", "Tischler/Schreiner"),
                            ("zimmerer", "Zimmerer"),
                            ("polsterer", "Polsterer"),
                            ("allgemein", "Gewerkübergreifend"),
                        ],
                        help_text="Gewerk für diesen Katalog",
                        max_length=20,
                    ),
                ),
                (
                    "gueltig_ab",
                    models.DateField(help_text="Ab wann ist dieser Katalog gültig?"),
                ),
                (
                    "gueltig_bis",
                    models.DateField(
                        blank=True,
                        help_text="Bis wann ist dieser Katalog gültig? (leer = unbegrenzt)",
                        null=True,
                    ),
                ),
                (
                    "ist_aktiv",
                    models.BooleanField(
                        default=True, help_text="Ist dieser Katalog aktiv?"
                    ),
                ),
                (
                    "ist_standard",
                    models.BooleanField(
                        default=False,
                        help_text="Ist dies der Standard-Katalog für neue Kalkulationen?",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        blank=True, help_text="Änderungen in dieser Version, Notizen"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erstellte_kataloge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vorgaenger_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vorherige Version dieses Katalogs (für Rollback)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nachfolger_versionen",
                        to="documents.bauteilkatalog",
                    ),
                ),
                (
                    "firma",
                    models.ForeignKey(
                        blank=True,
                        help_text="Firma, der dieser Katalog gehört (leer = global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bauteil_kataloge",
                        to="documents.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bauteil-Katalog",
                "verbose_name_plural": "Bauteil-Kataloge",
                "ordering": ["-gueltig_ab", "name"],
            },
        ),
        migrations.CreateModel(
            name="PauschaleAnwendung",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "berechnungsgrundlage",
                    models.JSONField(
                        help_text="\n        Grundlage für Berechnung (z.B. {'distanz_km': 75, 'entsorgung_m3': 2.5})\n        "
                    ),
                ),
                (
                    "menge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Menge (für 'pro_einheit'), leer für 'fest'",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "berechneter_betrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Errechneter Betrag in EUR",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "manuell_ueberschrieben",
                    models.BooleanField(
                        default=False,
                        help_text="Wurde der Betrag manuell überschrieben?",
                    ),
                ),
                (
                    "manueller_betrag",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manuell überschriebener Betrag",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notizen",
                    models.TextField(blank=True, help_text="Notizen zur Anwendung"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "extraction_result",
                    models.ForeignKey(
                        help_text="Extraction zu der diese Pauschale gehört",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauschale_anwendungen",
                        to="documents.extractionresult",
                    ),
                ),
                (
                    "pauschale",
                    models.ForeignKey(
                        help_text="Angewendete Pauschale-Regel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anwendungen",
                        to="documents.betriebspauschaleregel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pauschale-Anwendung",
                "verbose_name_plural": "Pauschale-Anwendungen",
                "ordering": ["-erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="StandardBauteil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artikel_nr",
                    models.CharField(
                        help_text="Eindeutige Artikel-Nummer (z.B. HF-12345 für Häfele-Artikel)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bezeichnung des Bauteils (z.B. 'Topfband 35mm Standard')",
                        max_length=200,
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        blank=True,
                        help_text="Detaillierte Beschreibung, technische Daten",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("beschlag", "Beschläge"),
                            ("verbinder", "Verbindungsmittel"),
                            ("kante", "Kantenbearbeitung"),
                            ("befestigung", "Befestigungsmittel"),
                            ("oberflaeche", "Oberflächenmaterial"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        help_text="Bauteil-Kategorie",
                        max_length=20,
                    ),
                ),
                (
                    "gewerke",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("tischler", "Tischler/Schreiner"),
                                ("zimmerer", "Zimmerer"),
                                ("polsterer", "Polsterer"),
                                ("allgemein", "Gewerkübergreifend"),
                            ],
                            max_length=20,
                        ),
                        help_text="Gewerke, für die dieses Bauteil relevant ist (Mehrfachauswahl)",
                        size=None,
                    ),
                ),
                (
                    "einheit",
                    models.CharField(
                        choices=[
                            ("stk", "Stück"),
                            ("lfm", "Laufmeter"),
                            ("m2", "Quadratmeter"),
                            ("kg", "Kilogramm"),
                            ("pkt", "Paket"),
                            ("set", "Set"),
                        ],
                        help_text="Mengeneinheit",
                        max_length=10,
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preis pro Einheit (netto, in Euro)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "lieferant",
                    models.CharField(
                        blank=True,
                        help_text="Hauptlieferant (z.B. Häfele, Wurth)",
                        max_length=100,
                    ),
                ),
                (
                    "lieferanten_artikel_nr",
                    models.CharField(
                        blank=True,
                        help_text="Artikel-Nummer beim Lieferanten",
                        max_length=100,
                    ),
                ),
                (
                    "ist_aktiv",
                    models.BooleanField(
                        default=True, help_text="Aktiv in Kalkulationen verwenden?"
                    ),
                ),
                (
                    "verfuegbar_ab",
                    models.DateField(
                        blank=True,
                        help_text="Ab wann ist das Bauteil verfügbar?",
                        null=True,
                    ),
                ),
                (
                    "verfuegbar_bis",
                    models.DateField(
                        blank=True,
                        help_text="Bis wann ist das Bauteil verfügbar? (z.B. Auslauf-Artikel)",
                        null=True,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "zusatz_daten",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusätzliche Daten (z.B. Gewicht, Abmessungen, technische Specs)",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erstellte_bauteile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard-Bauteil",
                "verbose_name_plural": "Standard-Bauteile",
                "ordering": ["kategorie", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeometrieBerechnung",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kanten_typ",
                    models.CharField(
                        choices=[
                            ("korpus_außen", "Korpus Außenkanten"),
                            ("korpus_innen", "Korpus Innenkanten"),
                            ("tür_außen", "Tür Außenkanten"),
                            ("einlegeboden_vorder", "Einlegeboden Vorderkante"),
                            ("einlegeboden_seite", "Einlegeboden Seitenkanten"),
                            ("schublade_außen", "Schublade Außenkanten"),
                            ("rueckseite", "Rückseite (meist unsichtbar)"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        help_text="Art der Kante",
                        max_length=30,
                    ),
                ),
                (
                    "formel",
                    models.TextField(
                        help_text="Formel für Berechnung (dokumentarisch)"
                    ),
                ),
                (
                    "berechnete_laenge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Automatisch berechnete Länge (in lfm)",
                        max_digits=10,
                    ),
                ),
                (
                    "ist_aktiviert",
                    models.BooleanField(
                        default=True,
                        help_text="Soll diese Kante bekanntet werden? (Checkbox für User)",
                    ),
                ),
                (
                    "manuell_ueberschrieben",
                    models.BooleanField(
                        default=False,
                        help_text="Hat der User die Länge manuell geändert?",
                    ),
                ),
                (
                    "manuelle_laenge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manuell überschriebene Länge (falls abweichend)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "komponenten_daten",
                    models.JSONField(
                        default=dict,
                        help_text="Ursprungs-Daten aus Extraktion (z.B. {'typ': 'Tür', 'höhe': 2.0, 'breite': 1.0})",
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "extraction_result",
                    models.ForeignKey(
                        help_text="Zugeordnetes Extraktions-Ergebnis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometrie_berechnungen",
                        to="documents.extractionresult",
                    ),
                ),
                (
                    "bauteil",
                    models.ForeignKey(
                        help_text="Bauteil, für das diese Geometrie berechnet wird",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometrie_berechnungen",
                        to="documents.standardbauteil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geometrie-Berechnung",
                "verbose_name_plural": "Geometrie-Berechnungen",
                "ordering": ["extraction_result", "kanten_typ"],
            },
        ),
        migrations.CreateModel(
            name="BauteilRegel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Beschreibung der Regel (z.B. 'Topfbänder pro Tür')",
                        max_length=200,
                    ),
                ),
                (
                    "regel_definition",
                    models.JSONField(
                        help_text='\n        JSON-Struktur für Regel-Definition.\n\n        Level 1 Beispiele:\n\n        1. MULTIPLY: {"operation": "MULTIPLY", "faktor": 3, "komponente": "Tür", "attribut": "anzahl"}\n           → 3 × Anzahl Türen\n\n        2. FIXED: {"operation": "FIXED", "wert": 10}\n           → Immer 10 Stück\n\n        3. ADD: {"operation": "ADD", "terme": [\n                    {"operation": "MULTIPLY", "faktor": 3, "komponente": "Tür", "attribut": "anzahl"},\n                    {"operation": "MULTIPLY", "faktor": 2, "komponente": "Schublade", "attribut": "anzahl"}\n                ]}\n           → (3 × Türen) + (2 × Schubladen)\n        '
                    ),
                ),
                (
                    "prioritaet",
                    models.IntegerField(
                        default=100,
                        help_text="Niedrigere Zahl = höhere Priorität (wird zuerst angewendet)",
                    ),
                ),
                (
                    "ist_aktiv",
                    models.BooleanField(default=True, help_text="Regel aktiv?"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "bauteil",
                    models.ForeignKey(
                        help_text="Bauteil, für das diese Regel gilt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeln",
                        to="documents.standardbauteil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bauteil-Regel",
                "verbose_name_plural": "Bauteil-Regeln",
                "ordering": ["bauteil", "prioritaet"],
            },
        ),
        migrations.CreateModel(
            name="BauteilKatalogPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "katalog_einzelpreis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preis in diesem Katalog (leer = Standard-Preis verwenden)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0, help_text="Sortier-Position im Katalog"
                    ),
                ),
                (
                    "ist_aktiv_in_katalog",
                    models.BooleanField(
                        default=True,
                        help_text="Ist dieses Bauteil in diesem Katalog aktiv?",
                    ),
                ),
                (
                    "katalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.bauteilkatalog",
                    ),
                ),
                (
                    "bauteil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.standardbauteil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Katalog-Position",
                "verbose_name_plural": "Katalog-Positionen",
                "ordering": ["katalog", "position", "bauteil"],
            },
        ),
        migrations.AddField(
            model_name="bauteilkatalog",
            name="bauteile",
            field=models.ManyToManyField(
                related_name="kataloge",
                through="documents.BauteilKatalogPosition",
                to="documents.standardbauteil",
            ),
        ),
        migrations.AddIndex(
            model_name="betriebspauschaleregel",
            index=models.Index(
                fields=["user", "ist_aktiv"], name="documents_b_user_id_423c87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="betriebspauschaleregel",
            index=models.Index(
                fields=["pauschale_typ", "ist_aktiv"],
                name="documents_b_pauscha_64be3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="betriebspauschaleregel",
            index=models.Index(
                fields=["gueltig_ab", "gueltig_bis"],
                name="documents_b_gueltig_c7044c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pauschaleanwendung",
            index=models.Index(
                fields=["extraction_result", "erstellt_am"],
                name="documents_p_extract_33db18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="standardbauteil",
            index=models.Index(
                fields=["kategorie", "ist_aktiv"], name="documents_s_kategor_0b651a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standardbauteil",
            index=models.Index(
                fields=["artikel_nr"], name="documents_s_artikel_08106f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geometrieberechnung",
            index=models.Index(
                fields=["extraction_result", "ist_aktiviert"],
                name="documents_g_extract_562692_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bauteilregel",
            index=models.Index(
                fields=["bauteil", "ist_aktiv"], name="documents_b_bauteil_4c5f3d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bauteilkatalogposition",
            unique_together={("katalog", "bauteil")},
        ),
        migrations.AddIndex(
            model_name="bauteilkatalog",
            index=models.Index(
                fields=["firma", "gewerk", "ist_aktiv"],
                name="documents_b_firma_i_5453fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bauteilkatalog",
            index=models.Index(
                fields=["gueltig_ab", "gueltig_bis"],
                name="documents_b_gueltig_545005_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bauteilkatalog",
            unique_together={("firma", "version", "gewerk")},
        ),
    ]
