# Generated by Django 5.0 on 2025-12-08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add performance indexes for frequently queried fields.

    Indexes added:
    1. Document: (user, status) - common filter combo
    2. Document: (created_at) - sorting optimization
    3. ExtractionFailurePattern: (detected_at) - date filtering
    4. ExtractionFailurePattern: (is_active, severity) - common filter combo
    5. ExtractionResult: (created_at) - sorting optimization

    Expected Impact: 50-70% faster filtered queries
    """

    dependencies = [
        ('documents', '0006_phase4c_multi_material_pauschalen'),
    ]

    operations = [
        # Document indexes
        migrations.AddIndex(
            model_name='document',
            index=models.Index(
                fields=['user', 'status'],
                name='documents_d_user_st_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(
                fields=['created_at'],
                name='documents_d_created_idx'
            ),
        ),

        # ExtractionFailurePattern indexes
        migrations.AddIndex(
            model_name='extractionfailurepattern',
            index=models.Index(
                fields=['detected_at'],
                name='pattern_detected_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='extractionfailurepattern',
            index=models.Index(
                fields=['is_active', 'severity'],
                name='pattern_active_sev_idx'
            ),
        ),

        # ExtractionResult indexes
        migrations.AddIndex(
            model_name='extractionresult',
            index=models.Index(
                fields=['created_at'],
                name='extraction_created_idx'
            ),
        ),
    ]
